CREATE SCHEMA IF NOT EXISTS game;
CREATE TABLE game.m_species (
    species_id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_species PRIMARY KEY,
    code varchar(24) NOT NULL CONSTRAINT uk_species_code UNIQUE,
    name varchar(64) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE game.m_species_evolution (
    species_id bigint NOT NULL CONSTRAINT fk_evolution_species REFERENCES game.m_species(species_id),
    evolution_stage integer NOT NULL CHECK (evolution_stage BETWEEN 1 AND 5),
    name varchar(64) NOT NULL,
    CONSTRAINT pk_species_evolution PRIMARY KEY (species_id, evolution_stage)
);
CREATE TABLE game.t_player (
    player_id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_player PRIMARY KEY,
    player_name varchar(64) NOT NULL CONSTRAINT uk_player_name UNIQUE,
    gold bigint NOT NULL DEFAULT 0 CHECK (gold >= 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE game.t_player_companion (
    player_companion_id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_player_companion PRIMARY KEY,
    player_id bigint NOT NULL CONSTRAINT fk_companion_player REFERENCES game.t_player(player_id),
    species_id bigint NOT NULL,
    evolution_stage integer NOT NULL,
    level integer NOT NULL DEFAULT 1 CHECK (level >= 1),
    exp bigint NOT NULL DEFAULT 0 CHECK (exp >= 0),
    bond integer NOT NULL DEFAULT 0 CHECK (bond >= 0),
    active boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT fk_companion_evolution FOREIGN KEY (species_id,evolution_stage)
      REFERENCES game.m_species_evolution(species_id,evolution_stage)
);
CREATE UNIQUE INDEX uk_companion_one_active ON game.t_player_companion(player_id) WHERE active;
CREATE INDEX ix_companion_player ON game.t_player_companion(player_id);
CREATE INDEX ix_companion_evolution ON game.t_player_companion(species_id,evolution_stage);
CREATE TABLE game.m_monster (
    monster_id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_monster PRIMARY KEY,
    code varchar(24) NOT NULL CONSTRAINT uk_monster_code UNIQUE,
    name varchar(64) NOT NULL,
    rarity varchar(24) NOT NULL,
    movement_profile varchar(24) NOT NULL CHECK (movement_profile IN ('GROUND','JUMP','FREE_2D','FLOATING','FLYING','EDGE','STATIC')),
    min_level integer NOT NULL CHECK (min_level >= 1),
    max_level integer NOT NULL CHECK (max_level >= min_level),
    encounter_weight integer NOT NULL CHECK (encounter_weight >= 0),
    use_yn boolean NOT NULL DEFAULT true
);
CREATE TABLE game.t_encounter (
    encounter_id uuid CONSTRAINT pk_encounter PRIMARY KEY,
    player_id bigint NOT NULL CONSTRAINT fk_encounter_player REFERENCES game.t_player(player_id),
    monster_id bigint NOT NULL CONSTRAINT fk_encounter_monster REFERENCES game.m_monster(monster_id),
    monster_level integer NOT NULL CHECK (monster_level >= 1),
    rarity varchar(24) NOT NULL,
    status varchar(24) NOT NULL CHECK (status IN ('ACTIVE','DEFEATED','CAPTURED','ESCAPED','EXPIRED')),
    spawned_at timestamptz NOT NULL,
    expires_at timestamptz NOT NULL CHECK (expires_at > spawned_at),
    resolved_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_encounter_resolution CHECK ((status = 'ACTIVE' AND resolved_at IS NULL) OR (status <> 'ACTIVE' AND resolved_at IS NOT NULL))
);
CREATE UNIQUE INDEX uk_encounter_one_active ON game.t_encounter(player_id) WHERE status = 'ACTIVE';
CREATE INDEX ix_encounter_player_created ON game.t_encounter(player_id,created_at DESC);
CREATE INDEX ix_encounter_monster ON game.t_encounter(monster_id);
CREATE INDEX ix_encounter_active_expiry ON game.t_encounter(expires_at) WHERE status='ACTIVE';
