CREATE TABLE game.t_monster_discovery (
    monster_discovery_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id bigint NOT NULL REFERENCES game.t_player(player_id),
    monster_id bigint NOT NULL REFERENCES game.m_monster(monster_id),
    first_discovered_at timestamptz NOT NULL,
    last_seen_at timestamptz NOT NULL,
    encounter_count bigint NOT NULL CHECK (encounter_count > 0),
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    UNIQUE(player_id, monster_id),
    CHECK (last_seen_at >= first_discovered_at),
    CHECK (updated_at >= created_at)
);
CREATE INDEX ix_discovery_monster ON game.t_monster_discovery(monster_id);
-- A receipt belongs to exactly one authoritative Encounter. Deleting test/history encounters
-- may remove receipts; an unknown/deleted Encounter can never be acknowledged again.
CREATE TABLE game.t_monster_discovery_receipt (
    encounter_id uuid PRIMARY KEY REFERENCES game.t_encounter(encounter_id) ON DELETE CASCADE,
    acknowledged_at timestamptz NOT NULL
);
