"""Project canonical local manifests into a static TS module; no PNG or activation changes."""
import argparse,json,re,math
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def unique(pairs):
    result={}
    for k,v in pairs:
        if k in result:raise ValueError('duplicate JSON key: '+k)
        result[k]=v
    return result
def read(path):return json.loads(path.read_text(),object_pairs_hook=unique)
def generate(root=ROOT):
    public=root/'public';entries={};keys={}
    companions=read(root/'src/entities/companions.json');monsters=read(root/'src/entities/monsters.json')
    candidates=[(url,species,int(stage)) for species,d in companions.items() for stage,url in d['stages'].items()]
    candidates += [(d['assetRoot']+'/manifest.json',code.lower(),1) for code,d in monsters.items()]
    for url,species,stage in sorted(candidates):
        if not re.fullmatch(r'/assets/(creatures/[a-z][a-z0-9_]*/stage[0-9]{2}|monsters/[a-z][a-z0-9_]*)/manifest.json',url):raise ValueError('noncanonical local path: '+url)
        if url.casefold() in keys:raise ValueError('duplicate/case path: '+url)
        keys[url.casefold()]=url;path=public/url.lstrip('/')
        if not path.resolve().is_relative_to(public.resolve()):raise ValueError('escaped public root')
        if not path.exists():continue # Metadata presence never activates an unsupplied clip.
        current=public
        for part in path.relative_to(public).parts:
            matches=[p.name for p in current.iterdir() if p.name.casefold()==part.casefold()]
            if matches!=[part]:raise ValueError('case mismatch: '+url)
            current=current/part
        m=read(path)
        if (m.get('species'),m.get('stage'),m.get('canvas'),m.get('anchor'))!=(species,stage,{'width':256,'height':256},{'x':.5,'y':1}):raise ValueError('identity/canvas/anchor: '+url)
        def positive(x):return type(x) in (int,float) and math.isfinite(x) and x>0
        if not positive(m.get('display',{}).get('width')) or not isinstance(m.get('animations'),dict) or not m['animations']:raise ValueError('invalid display/clips')
        for name,c in m['animations'].items():
            if not re.fullmatch('[a-z][a-z0-9_-]*',name) or type(c.get('frames')) is not int or not 1<=c['frames']<=256 or not positive(c.get('frameDuration')) or type(c.get('loop')) is not bool:raise ValueError('invalid clip: '+url)
        entries[url]=m
    # The current MOA IDLE production delivery requires this metadata; other slots stay optional.
    if '/assets/creatures/moa/stage01/manifest.json' not in entries:raise ValueError('missing MOA production IDLE manifest')
    return '// Generated by scripts/sync_animation_manifests.py; edit canonical public manifests only.\nexport const animationManifests: Readonly<Record<string, unknown>> = '+json.dumps(entries,indent=2,sort_keys=True)+';\n'
def main():
    p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');a=p.parse_args();text=generate();output=ROOT/'src/animation/generated-manifests.ts'
    if a.check:
        if not output.exists() or output.read_text()!=text:raise SystemExit('Stale animation registry: run npm run sync:animation')
    else:output.write_text(text)
if __name__=='__main__':main()
