// Generated by scripts/sync_animation_manifests.py; edit canonical public manifests only.
export const animationManifests: Readonly<Record<string, unknown>> = {
  "/assets/creatures/moa/stage01/manifest.json": {
    "anchor": {
      "x": 0.5,
      "y": 1
    },
    "animations": {
      "blink": {
        "frameDuration": 90,
        "frames": 3,
        "loop": false
      },
      "breath": {
        "frameDuration": 450,
        "frames": 4,
        "loop": true
      },
      "idle": {
        "frameDuration": 100,
        "frames": 6,
        "loop": true
      },
      "look": {
        "frameDuration": 120,
        "frames": 4,
        "loop": true
      },
      "react": {
        "frameDuration": 80,
        "frames": 6,
        "loop": false
      },
      "sit": {
        "frameDuration": 120,
        "frames": 4,
        "loop": true
      },
      "sleep": {
        "frameDuration": 150,
        "frames": 6,
        "loop": true
      },
      "walk": {
        "frameDuration": 80,
        "frames": 8,
        "loop": true
      }
    },
    "canvas": {
      "height": 256,
      "width": 256
    },
    "display": {
      "width": 130
    },
    "idleSequences": {
      "blink": "blink",
      "blinkIntervalMs": [
        3000,
        7000
      ],
      "breath": "breath"
    },
    "species": "moa",
    "stage": 1
  },
  "/assets/creatures/moa/stage02/manifest.json": {
    "anchor": {
      "x": 0.5,
      "y": 1
    },
    "animations": {
      "idle": {
        "frameDuration": 100,
        "frames": 6,
        "loop": true
      },
      "look": {
        "frameDuration": 120,
        "frames": 4,
        "loop": true
      },
      "react": {
        "frameDuration": 80,
        "frames": 6,
        "loop": false
      },
      "sit": {
        "frameDuration": 120,
        "frames": 4,
        "loop": true
      },
      "sleep": {
        "frameDuration": 150,
        "frames": 6,
        "loop": true
      },
      "walk": {
        "frameDuration": 80,
        "frames": 8,
        "loop": true
      }
    },
    "canvas": {
      "height": 256,
      "width": 256
    },
    "display": {
      "width": 130
    },
    "species": "moa",
    "stage": 2
  },
  "/assets/creatures/nox/stage01/manifest.json": {
    "anchor": {
      "x": 0.5,
      "y": 1
    },
    "animations": {
      "idle": {
        "frameDuration": 100,
        "frames": 6,
        "loop": true
      },
      "look": {
        "frameDuration": 120,
        "frames": 4,
        "loop": true
      },
      "react": {
        "frameDuration": 80,
        "frames": 6,
        "loop": false
      },
      "sit": {
        "frameDuration": 120,
        "frames": 4,
        "loop": true
      },
      "sleep": {
        "frameDuration": 150,
        "frames": 6,
        "loop": true
      },
      "walk": {
        "frameDuration": 80,
        "frames": 8,
        "loop": true
      }
    },
    "canvas": {
      "height": 256,
      "width": 256
    },
    "display": {
      "width": 130
    },
    "species": "nox",
    "stage": 1
  },
  "/assets/creatures/ruu/stage01/manifest.json": {
    "anchor": {
      "x": 0.5,
      "y": 1
    },
    "animations": {
      "idle": {
        "frameDuration": 100,
        "frames": 6,
        "loop": true
      },
      "look": {
        "frameDuration": 120,
        "frames": 4,
        "loop": true
      },
      "react": {
        "frameDuration": 80,
        "frames": 6,
        "loop": false
      },
      "sit": {
        "frameDuration": 120,
        "frames": 4,
        "loop": true
      },
      "sleep": {
        "frameDuration": 150,
        "frames": 6,
        "loop": true
      },
      "walk": {
        "frameDuration": 80,
        "frames": 8,
        "loop": true
      }
    },
    "canvas": {
      "height": 256,
      "width": 256
    },
    "display": {
      "width": 130
    },
    "species": "ruu",
    "stage": 1
  },
  "/assets/monsters/chirp/manifest.json": {
    "anchor": {
      "x": 0.5,
      "y": 1
    },
    "animations": {
      "fly": {
        "frameDuration": 90.0,
        "frames": 6,
        "loop": true
      },
      "glide": {
        "frameDuration": 300.0,
        "frames": 2,
        "loop": true
      },
      "hover": {
        "frameDuration": 400.0,
        "frames": 4,
        "loop": true
      }
    },
    "canvas": {
      "height": 256,
      "width": 256
    },
    "display": {
      "width": 82
    },
    "species": "chirp",
    "stage": 1
  },
  "/assets/monsters/mello/manifest.json": {
    "anchor": {
      "x": 0.5,
      "y": 1
    },
    "animations": {
      "jump": {
        "frameDuration": 80,
        "frames": 8,
        "loop": false
      }
    },
    "canvas": {
      "height": 256,
      "width": 256
    },
    "display": {
      "width": 82
    },
    "jumpPhases": [
      "NEUTRAL",
      "CROUCH",
      "LAUNCH",
      "ASCEND",
      "APEX",
      "DESCEND",
      "LAND",
      "SETTLE"
    ],
    "species": "mello",
    "stage": 1
  },
  "/assets/monsters/pip/manifest.json": {
    "anchor": {
      "x": 0.5,
      "y": 1
    },
    "animations": {
      "idle": {
        "frameDuration": 450,
        "frames": 4,
        "loop": true
      },
      "react": {
        "frameDuration": 80,
        "frames": 6,
        "loop": false
      },
      "walk": {
        "frameDuration": 80,
        "frames": 8,
        "loop": true
      }
    },
    "canvas": {
      "height": 256,
      "width": 256
    },
    "display": {
      "width": 82
    },
    "species": "pip",
    "stage": 1
  }
};
